import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NavigationMenuDemo } from "@/components/NavigationMenuDemo";
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/contexts/authContexts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AnimatedThemeToggler className="fixed top-4 right-4 z-50" />
          <NavigationMenuDemo />
          {children}
          <Toaster richColors position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
