export const CATEGORIAS_NEGOCIO = [
  { value: "alimentos_bebidas", label: "Alimentos y Bebidas" },
  { value: "tecnologia_electronica", label: "Tecnología y Electrónica" },
  { value: "ropa_moda", label: "Ropa y Moda" },
  { value: "hogar_decoracion", label: "Hogar y Decoración" },
  { value: "salud_belleza", label: "Salud y Belleza" },
  { value: "deportes_fitness", label: "Deportes y Fitness" },
  { value: "automotriz", label: "Automotriz" },
  { value: "construccion_ferreteria", label: "Construcción y Ferretería" },
  { value: "papeleria_oficina", label: "Papelería y Oficina" },
  { value: "juguetes_infantil", label: "Juguetes e Infantil" },
  { value: "mascotas", label: "Mascotas" },
  { value: "libros_educacion", label: "Libros y Educación" },
  { value: "jardineria_plantas", label: "Jardinería y Plantas" },
  { value: "muebles", label: "Muebles" },
  { value: "joyeria_accesorios", label: "Joyería y Accesorios" },
  { value: "servicios_profesionales", label: "Servicios Profesionales" },
  { value: "entretenimiento", label: "Entretenimiento" },
  { value: "arte_artesania", label: "Arte y Artesanía" },
  { value: "musica_instrumentos", label: "Música e Instrumentos" },
  { value: "eventos_celebraciones", label: "Eventos y Celebraciones" },
  { value: "turismo_viajes", label: "Turismo y Viajes" },
  { value: "inmobiliaria", label: "Inmobiliaria" },
  { value: "farmacia_medicamentos", label: "Farmacia y Medicamentos" },
  { value: "limpieza_higiene", label: "Limpieza e Higiene" },
  { value: "otros", label: "Otros" },
] as const;

export type CategoriaNegocio = typeof CATEGORIAS_NEGOCIO[number]["value"];
